# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1094, 688)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./20200401004730.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 3)
        self.titleLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.titleLineEdit.setMinimumSize(QtCore.QSize(111, 0))
        self.titleLineEdit.setMaximumSize(QtCore.QSize(111, 16777215))
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.gridLayout.addWidget(self.titleLineEdit, 0, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 1, 3, 1, 1)
        self.enableTitleCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.enableTitleCheckBox.setObjectName("enableTitleCheckBox")
        self.gridLayout.addWidget(self.enableTitleCheckBox, 1, 4, 1, 1)
        self.checkButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkButton.setObjectName("checkButton")
        self.gridLayout.addWidget(self.checkButton, 1, 5, 1, 1)
        self.addTitleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addTitleBtn.setMinimumSize(QtCore.QSize(111, 0))
        self.addTitleBtn.setMaximumSize(QtCore.QSize(111, 16777215))
        self.addTitleBtn.setObjectName("addTitleBtn")
        self.gridLayout.addWidget(self.addTitleBtn, 1, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 1, 1, 5)
        self.delTitleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delTitleBtn.setMinimumSize(QtCore.QSize(111, 0))
        self.delTitleBtn.setMaximumSize(QtCore.QSize(111, 16777215))
        self.delTitleBtn.setObjectName("delTitleBtn")
        self.gridLayout.addWidget(self.delTitleBtn, 2, 6, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 3, 0, 1, 6)
        self.titleListView = QtWidgets.QListView(self.centralwidget)
        self.titleListView.setMinimumSize(QtCore.QSize(111, 0))
        self.titleListView.setMaximumSize(QtCore.QSize(111, 16777215))
        self.titleListView.setObjectName("titleListView")
        self.gridLayout.addWidget(self.titleListView, 3, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "查重工具"))
        self.label_3.setText(_translate("MainWindow", "Note:【查重前】请确认每个题目编号后为、或.号，并且选项ABCD的编号为纯文字类型，以图片形式承载的ABCD选项暂时无法处理"))
        self.label.setText(_translate("MainWindow", "试卷路径:"))
        self.browseButton.setText(_translate("MainWindow", "浏览"))
        self.enableTitleCheckBox.setText(_translate("MainWindow", "启用标题查找"))
        self.checkButton.setText(_translate("MainWindow", "开始查重"))
        self.addTitleBtn.setText(_translate("MainWindow", "添加标题"))
        self.label_2.setText(_translate("MainWindow", "进度："))
        self.delTitleBtn.setText(_translate("MainWindow", "删除标题"))

